### PR TITLE
Fix on shebang

### PR DESCRIPTION
**Pull request by Rudolph-afk**
Shebang was missing exclamation mark (!)

### CODE REVIEW

**Comment by mourisl** [comment]
Hi @Rudolph-afk , thank you for finding the bug. Is it possible to just pull request for the first commit about the "!" issue? I intentionally keep the execution permission from the auxiliary scripts to distinguish them from the core trust4 executables.

**Comment by Rudolph-afk** [comment]
I will try to revert the second commit. Is it not possible for you to resolve 1 commit from the pull request?

**Comment by mourisl** [comment]
I tried several times, but could not find the button to merge the pull request or create a pull request from that commit..

**Comment by Rudolph-afk** [comment]
I managed to delete the last commit. Should be okay now

**Comment by mourisl** [comment]
Thank you! It is merged.

**Pull request merged**
